// process.exit(1)
throw new Error('error!')